# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GenericsAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GenericsAPI
	pod 'Alamofire', '4.4.0'
	pod 'Material', '3.1.8'
	pod 'IQKeyboardManagerSwift', '6.5.10'
	pod 'Kingfisher', '~> 7.0'

end
